---
# tasks file for configuring firewall
- name: Make sure firewalld is installed
  ansible.builtin.yum:
    name: firewalld
    state: latest

- name: Make sure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Open Satellite related ports on the firewall
  ansible.posix.firewalld:
    service: '{{ item }}'
    permanent: true
    state: enabled
    immediate: true
  with_items: '{{ firewalld_ports }}' 
