---
# tasks file for ansible-role-satellite

- name: Register host with CDN
  include_tasks: rhsm.yml

- name: Execute firewalld tasks
  include_tasks: firewalld.yml

- name: Update and install Satellite
  include_tasks: satellite.yml
