---
# tasks file for registering host to red hat cdn
- name: Register with red hat cdn and attach satellite infrastructure subscription
  community.general.redhat_subscription:
    username: '{{ rhn_username }}'
    password: '{{ rhn_password }}'
    state: present
    pool: '^(Red Hat Satellite Infrastructure Subscription)$'

- name: Disable all RHSM repositories
  community.general.rhsm_repository:
    name: '*'
    state: disabled

- name: Enable all repositories needed for satellite {{sat_version}} on RHEL 7
  community.general.rhsm_repository:
    name: '{{ item }}'
    state: enabled
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-satellite-{{sat_version}}-rpms
    - rhel-7-server-satellite-maintenance-6-rpms
    - rhel-server-rhscl-7-rpms
    - rhel-7-server-ansible-2.9-rpms
  when: ansible_distribution_major_version == '7' and sat_version >= 6.11

- name: Enable all repositories needed for satellite {{sat_version}} on RHEL 8
  community.general.rhsm_repository:
    name: '{{ item }}'
    state: enabled
  with_items:
    - rhel-8-for-x86_64-appstream-rpms
    - rhel-8-for-x86_64-baseos-rpms
    - satellite-{{sat_version}}-for-rhel-8-x86_64-rpms
    - satellite-maintenance-{{sat_version}}-for-rhel-8-x86_64-rpms
  when: ansible_distribution_major_version == '8' and sat_version >= 6.11

- name: Enable ruby:2.7 and postgresql:12 modules for RHEL 8
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - '@ruby:2.7'
    - '@postgresql:12'
  when: ansible_distribution_major_version == '8' and sat_version >= 6.11

# Workaround for @satellite:el8 until https://github.com/ansible/ansible/pull/76277 is resolved
- name: Enable satellite:el8 module for RHEL 8
  ansible.builtin.copy:
    dest: '/etc/dnf/modules.d/{{ item }}'
    src: 'files/{{ item }}'
  with_items:
    - pki-core.module
    - pki-deps.module
    - satellite.module
  when: ansible_distribution_major_version == '8' and sat_version >= 6.11
