---
# tasks file for updating host and install satellite

- name: Upgrade all host packages
  yum:
    name: '*'
    state: latest

- name: Install the latest version of Satellite
  yum:
    name: satellite
    state: latest

- name: Run the Satellite installer
  command: |
      satellite-installer --scenario satellite
      --foreman-initial-admin-username {{ sat_username }}
      --foreman-initial-admin-password {{ sat_password }}
      --foreman-proxy-puppetca true
      --foreman-proxy-tftp true
      --enable-foreman-plugin-discovery
